name: libra-web-tools
type: node
up:
  - node:
      version: v12.13.1
      yarn: 1.21.1
commands:
  __default__: start
  build: yarnpkg build
  check: yarnpkg check
  lint: yarnpkg lint
  start: echo "Running libra-web-tools is not really a concept that makes sense."
  test: yarnpkg test
  generate: yarnpkg generate
