name: libra-web-tools
type: node
up:
  - node:
      version: v12.13.1
      yarn: 1.21.1
commands:
  __default__: server
  build: yarnpkg build
  check: yarnpkg check
  lint: yarnpkg lint
  server:
    aliases: [start, s]
    run: yarnpkg playground
  test: yarnpkg test
  generate: yarnpkg generate
